-- ============================================================================
--  Volea — one-shot database setup
--  GENERATED by scripts/bundle-sql.mjs — edit supabase/migrations/* instead.
--
--  Paste this whole file into the Supabase SQL Editor and run it once.
--
--  Do NOT assume it is atomic: the editor can commit earlier statements and
--  then stop on a later error, leaving a half-applied database. If it reports
--  an error, read it before re-running — the guard below will refuse a second
--  full run once the tables exist.
--
--  The seed prints a clubs/courts count, and the final block drives four
--  players through queue -> match -> court -> result -> rating and raises if
--  anything is wrong. Seeing both means a verified install.
-- ============================================================================

do $guard$
begin
  if exists (
    select 1 from pg_tables where schemaname = 'public' and tablename = 'matches'
  ) then
    raise exception
      'Volea is already installed here. Drop the existing tables first if you meant to reinstall.';
  end if;
end $guard$;

-- ============================ init ============================

-- Volea — padel matchmaking platform
-- Everything lives in `public` — this project hosts Volea and nothing else.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- enums
create type public.play_mode      as enum ('doubles','singles');
create type public.court_side     as enum ('left','right','both');
create type public.queue_status   as enum ('waiting','matched','expired','cancelled');
create type public.match_status   as enum ('scheduled','completed','cancelled');
create type public.match_origin   as enum ('queue','direct','tournament');
create type public.club_status    as enum ('pending','active','inactive');
create type public.tourney_status as enum ('draft','open','locked','live','completed','cancelled');

-- Padel's 1.0-7.0 ladder, derived from a hidden Elo so it self-corrects on results.
-- 800 -> 1.0 (first session), 1000 -> 2.0 (new player default), 2300+ -> 7.0 (pro).
create or replace function public.rating_to_level(p_rating int)
returns numeric language sql immutable
set search_path = pg_catalog, pg_temp as $fn$
  select round(least(7.0, greatest(1.0, 1.0 + (p_rating - 800)::numeric / 250)) * 2) / 2;
$fn$;

-- ---------------------------------------------------------------- profiles
create table public.profiles (
  id             uuid primary key references auth.users(id) on delete cascade,
  username       text not null,
  full_name      text not null,
  avatar_url     text,
  bio            text,
  city           text,
  country        text,
  lat            double precision,
  lng            double precision,
  preferred_side public.court_side not null default 'both',
  rating         int not null default 1000 check (rating between 100 and 4000),
  level          numeric(2,1) generated always as (public.rating_to_level(rating)) stored,
  matches_played int not null default 0,
  matches_won    int not null default 0,
  is_club_owner  boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint username_format check (username ~ '^[a-z0-9_]{3,20}$')
);
create unique index profiles_username_key on public.profiles (lower(username));
create index profiles_city_rating_idx on public.profiles (lower(city), rating desc);

-- ---------------------------------------------------------------- clubs & courts
create table public.clubs (
  id                     uuid primary key default gen_random_uuid(),
  owner_id               uuid references auth.users(id) on delete set null,
  name                   text not null,
  slug                   text not null unique,
  description            text,
  address                text,
  city                   text not null,
  country                text,
  lat                    double precision not null,
  lng                    double precision not null,
  timezone               text not null default 'UTC',
  phone                  text,
  email                  text,
  image_url              text,
  price_per_hour_cents   int not null default 0 check (price_per_hour_cents >= 0),
  currency               text not null default 'PKR',
  opens_at               time not null default '07:00',
  closes_at              time not null default '23:00',
  amenities              text[] not null default '{}',
  status                 public.club_status not null default 'active',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
create index clubs_city_idx  on public.clubs (lower(city)) where status = 'active';
create index clubs_owner_idx on public.clubs (owner_id);

create table public.courts (
  id        uuid primary key default gen_random_uuid(),
  club_id   uuid not null references public.clubs(id) on delete cascade,
  name      text not null,
  indoor    boolean not null default false,
  surface   text not null default 'artificial grass',
  is_active boolean not null default true,
  unique (club_id, name)
);
create index courts_club_idx on public.courts (club_id) where is_active;

-- ---------------------------------------------------------------- matches
create table public.matches (
  id                uuid primary key default gen_random_uuid(),
  club_id           uuid not null references public.clubs(id) on delete restrict,
  court_id          uuid not null references public.courts(id) on delete restrict,
  mode              public.play_mode not null default 'doubles',
  starts_at         timestamptz not null,
  ends_at           timestamptz not null,
  status            public.match_status not null default 'scheduled',
  origin            public.match_origin not null default 'queue',
  price_total_cents int not null default 0,
  currency          text not null default 'PKR',
  winning_team      smallint check (winning_team in (1,2)),
  score             jsonb,
  reported_by       uuid references public.profiles(id) on delete set null,
  completed_at      timestamptz,
  created_at        timestamptz not null default now(),
  constraint match_window check (ends_at > starts_at)
);
-- One booking per court per slot. Guarantees we never double-book an owner's court.
create unique index matches_court_slot_key on public.matches (court_id, starts_at)
  where status <> 'cancelled';
create index matches_club_time_idx on public.matches (club_id, starts_at desc);

create table public.match_players (
  match_id      uuid not null references public.matches(id) on delete cascade,
  player_id     uuid not null references public.profiles(id) on delete cascade,
  team          smallint not null check (team in (1,2)),
  rating_before int,
  rating_after  int,
  primary key (match_id, player_id)
);
create index match_players_player_idx on public.match_players (player_id);

-- ---------------------------------------------------------------- matchmaking queue
create table public.queue_entries (
  id           uuid primary key default gen_random_uuid(),
  player_id    uuid not null references public.profiles(id) on delete cascade,
  play_date    date not null,
  window_start time not null,
  window_end   time not null,
  mode         public.play_mode not null default 'doubles',
  club_id      uuid references public.clubs(id) on delete cascade, -- null = surprise me
  city         text,
  min_level    numeric(2,1) not null default 1.0,
  max_level    numeric(2,1) not null default 7.0,
  status       public.queue_status not null default 'waiting',
  match_id     uuid references public.matches(id) on delete set null,
  created_at   timestamptz not null default now(),
  constraint queue_window check (window_end > window_start),
  constraint queue_level_range check (max_level >= min_level)
);
-- A player can only sit in one live queue per day.
create unique index queue_one_waiting_per_day on public.queue_entries (player_id, play_date)
  where status = 'waiting';
create index queue_search_idx on public.queue_entries (play_date, mode, status);

-- ---------------------------------------------------------------- tournaments
create table public.tournaments (
  id                     uuid primary key default gen_random_uuid(),
  club_id                uuid not null references public.clubs(id) on delete cascade,
  name                   text not null,
  slug                   text not null unique,
  description            text,
  mode                   public.play_mode not null default 'doubles',
  size                   int not null check (size in (4,8,16,32)),
  entry_fee_cents        int not null default 0,
  currency               text not null default 'PKR',
  starts_at              timestamptz not null,
  registration_closes_at timestamptz not null,
  status                 public.tourney_status not null default 'open',
  champion_team_id       uuid,
  created_by             uuid references public.profiles(id) on delete set null,
  created_at             timestamptz not null default now()
);
create index tournaments_status_idx on public.tournaments (status, starts_at);

create table public.tournament_teams (
  id            uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  name          text not null,
  player1_id    uuid not null references public.profiles(id) on delete cascade,
  player2_id    uuid references public.profiles(id) on delete cascade,
  seed          int,
  created_at    timestamptz not null default now(),
  unique (tournament_id, player1_id)
);
alter table public.tournaments
  add constraint tournaments_champion_fk
  foreign key (champion_team_id) references public.tournament_teams(id) on delete set null;

create table public.tournament_matches (
  id             uuid primary key default gen_random_uuid(),
  tournament_id  uuid not null references public.tournaments(id) on delete cascade,
  round          int not null,
  slot           int not null,
  team1_id       uuid references public.tournament_teams(id) on delete set null,
  team2_id       uuid references public.tournament_teams(id) on delete set null,
  winner_team_id uuid references public.tournament_teams(id) on delete set null,
  match_id       uuid references public.matches(id) on delete set null,
  score          jsonb,
  scheduled_at   timestamptz,
  unique (tournament_id, round, slot)
);
create index tmatches_tournament_idx on public.tournament_matches (tournament_id, round, slot);

comment on table public.queue_entries is 'A player advertising a time window. The matcher pairs overlapping windows into a match and assigns a free court.';
comment on table public.matches is 'A booked court slot with its players. price_total_cents is a snapshot of club pricing so later repricing never rewrites revenue history.';
comment on column public.profiles.level is 'Derived 1.0-7.0 padel level. Never write directly — it follows `rating`.';

-- ============================ engine ============================

-- Volea — matchmaking engine, rating maths, brackets, club analytics and RLS.

-- ---------------------------------------------------------------- signup hook
-- Fires for every auth user. Deliberately non-fatal: a profile that fails to
-- materialise must never block somebody's signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $fn$
begin
  insert into public.profiles (id, username, full_name, city, country)
  values (
    new.id,
    coalesce(
      nullif(lower(new.raw_user_meta_data->>'username'), ''),
      'p' || substr(replace(new.id::text, '-', ''), 1, 12)
    ),
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), 'Player'),
    nullif(new.raw_user_meta_data->>'city', ''),
    nullif(new.raw_user_meta_data->>'country', '')
  )
  on conflict (id) do nothing;
  return new;
exception when others then
  return new;
end $fn$;

drop trigger if exists on_auth_user_created_volea on auth.users;
create trigger on_auth_user_created_volea
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------- matchmaking
-- Joins the queue and attempts to fill a match in the same transaction.
-- Returns the caller's queue row: status 'waiting' means still looking,
-- 'matched' means match_id is populated.
create or replace function public.join_queue(
  p_play_date    date,
  p_window_start time,
  p_window_end   time,
  p_mode         public.play_mode default 'doubles',
  p_club_id      uuid default null,
  p_min_level    numeric default 1.0,
  p_max_level    numeric default 7.0
)
returns public.queue_entries
language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_dur      constant interval := interval '90 minutes';  -- a padel slot
  v_me       uuid := auth.uid();
  v_required int;
  v_city     text;
  v_level    numeric;
  v_entry    public.queue_entries;
  v_cand     record;
  v_slot     record;
  v_ids      uuid[] := '{}';
  v_players  uuid[];
  v_pinned   uuid := p_club_id;
  v_ov_start time := p_window_start;
  v_ov_end   time := p_window_end;
  v_match_id uuid;
begin
  if v_me is null then
    raise exception 'Sign in to join the queue.' using errcode = '28000';
  end if;
  if p_window_end <= p_window_start then
    raise exception 'The end of your window must be after the start.' using errcode = '22023';
  end if;
  if p_window_start + v_dur > p_window_end then
    raise exception 'Give us at least a 90 minute window — that is one padel slot.' using errcode = '22023';
  end if;

  select p.level, coalesce(p.city, c.city)
    into v_level, v_city
  from public.profiles p
  left join public.clubs c on c.id = p_club_id
  where p.id = v_me;

  if v_city is null and p_club_id is null then
    raise exception 'Set your city on your profile, or pick a specific club.' using errcode = '22023';
  end if;

  v_required := case when p_mode = 'doubles' then 4 else 2 end;

  insert into public.queue_entries
    (player_id, play_date, window_start, window_end, mode, club_id, city, min_level, max_level)
  values
    (v_me, p_play_date, p_window_start, p_window_end, p_mode, p_club_id, v_city, p_min_level, p_max_level)
  returning * into v_entry;

  -- Gather compatible players already waiting. `skip locked` means two people
  -- hitting the button at the same instant can never claim the same partner.
  for v_cand in
    select q.id, q.player_id, q.club_id, q.window_start, q.window_end
    from public.queue_entries q
    join public.profiles p on p.id = q.player_id
    where q.status = 'waiting'
      and q.id <> v_entry.id
      and q.play_date = p_play_date
      and q.mode = p_mode
      and q.window_start < p_window_end
      and q.window_end   > p_window_start
      -- club compatibility: nobody pinned a conflicting venue
      and (q.club_id is null or p_club_id is null or q.club_id = p_club_id)
      -- when neither pinned a club, they must at least be in the same city
      and (q.club_id is not null or p_club_id is not null or lower(q.city) = lower(v_city))
      -- level bands must satisfy BOTH players
      and p.level between p_min_level and p_max_level
      and v_level between q.min_level and q.max_level
    order by q.created_at
    for update of q skip locked
  loop
    exit when coalesce(array_length(v_ids, 1), 0) >= v_required - 1;
    -- only accept a candidate if the shared window still fits a full slot
    if greatest(v_ov_start, v_cand.window_start) + v_dur <= least(v_ov_end, v_cand.window_end) then
      v_ov_start := greatest(v_ov_start, v_cand.window_start);
      v_ov_end   := least(v_ov_end, v_cand.window_end);
      v_ids      := v_ids || v_cand.id;
      v_pinned   := coalesce(v_pinned, v_cand.club_id);
    end if;
  end loop;

  if coalesce(array_length(v_ids, 1), 0) < v_required - 1 then
    return v_entry;  -- still hunting
  end if;

  -- Pick a free court. Random among whatever is genuinely available, which is
  -- what "assign us a court" means to a player.
  select s.* into v_slot
  from (
    select cl.id as club_id, c.id as court_id,
           cl.price_per_hour_cents, cl.currency,
           ((p_play_date + v_ov_start) at time zone cl.timezone) as starts_at,
           ((p_play_date + v_ov_start) at time zone cl.timezone) + v_dur as ends_at
    from public.clubs cl
    join public.courts c on c.club_id = cl.id and c.is_active
    where cl.status = 'active'
      and (v_pinned is null or cl.id = v_pinned)
      and (v_pinned is not null or lower(cl.city) = lower(v_city))
      and v_ov_start >= cl.opens_at
      and v_ov_start + v_dur <= cl.closes_at
  ) s
  where not exists (
    select 1 from public.matches m
    where m.court_id = s.court_id
      and m.status <> 'cancelled'
      and m.starts_at < s.ends_at
      and m.ends_at   > s.starts_at
  )
  order by random()
  limit 1;

  if not found then
    return v_entry;  -- everyone is free but every court is taken; keep waiting
  end if;

  insert into public.matches
    (club_id, court_id, mode, starts_at, ends_at, origin, price_total_cents, currency)
  values
    (v_slot.club_id, v_slot.court_id, p_mode, v_slot.starts_at, v_slot.ends_at, 'queue',
     round(v_slot.price_per_hour_cents * 1.5), v_slot.currency)
  returning id into v_match_id;

  -- Balanced teams: strongest pairs with weakest (1+4 vs 2+3). Keeps games close.
  select array_agg(q.player_id order by p.rating desc)
    into v_players
  from public.queue_entries q
  join public.profiles p on p.id = q.player_id
  where q.id = any(v_ids || v_entry.id);

  insert into public.match_players (match_id, player_id, team, rating_before)
  select v_match_id, pid,
         case
           when p_mode = 'singles' then (case when ord = 1 then 1 else 2 end)
           else (case when ord in (1, 4) then 1 else 2 end)
         end,
         pr.rating
  from unnest(v_players) with ordinality as t(pid, ord)
  join public.profiles pr on pr.id = t.pid;

  update public.queue_entries
     set status = 'matched', match_id = v_match_id
   where id = any(v_ids || v_entry.id);

  select * into v_entry from public.queue_entries where id = v_entry.id;
  return v_entry;
end $fn$;

create or replace function public.leave_queue(p_entry_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
begin
  update public.queue_entries
     set status = 'cancelled'
   where id = p_entry_id and player_id = auth.uid() and status = 'waiting';
end $fn$;

-- ---------------------------------------------------------------- results & rating
-- Elo over team averages; every player on a side moves by the same delta.
create or replace function public.report_match_result(
  p_match_id     uuid,
  p_winning_team smallint,
  p_score        jsonb default null
)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_k    constant int := 32;
  v_me   uuid := auth.uid();
  v_r1   numeric;
  v_r2   numeric;
  v_exp1 numeric;
  v_d1   int;
  v_d2   int;
begin
  if not exists (select 1 from public.match_players where match_id = p_match_id and player_id = v_me) then
    raise exception 'Only players in this match can report its result.' using errcode = '42501';
  end if;
  if not exists (select 1 from public.matches where id = p_match_id and status = 'scheduled') then
    raise exception 'This match has already been settled.' using errcode = '22023';
  end if;
  if p_winning_team not in (1, 2) then
    raise exception 'Winning team must be 1 or 2.' using errcode = '22023';
  end if;

  select avg(pr.rating) filter (where mp.team = 1),
         avg(pr.rating) filter (where mp.team = 2)
    into v_r1, v_r2
  from public.match_players mp
  join public.profiles pr on pr.id = mp.player_id
  where mp.match_id = p_match_id;

  v_exp1 := 1.0 / (1.0 + power(10.0, (v_r2 - v_r1) / 400.0));
  v_d1   := round(v_k * ((case when p_winning_team = 1 then 1 else 0 end) - v_exp1));
  v_d2   := -v_d1;

  update public.profiles p
     set rating         = greatest(100, least(4000, p.rating + case when mp.team = 1 then v_d1 else v_d2 end)),
         matches_played = p.matches_played + 1,
         matches_won    = p.matches_won + case when mp.team = p_winning_team then 1 else 0 end,
         updated_at     = now()
  from public.match_players mp
  where mp.match_id = p_match_id and mp.player_id = p.id;

  update public.match_players mp
     set rating_after = pr.rating
  from public.profiles pr
  where mp.match_id = p_match_id and pr.id = mp.player_id;

  update public.matches
     set status = 'completed', winning_team = p_winning_team, score = p_score,
         reported_by = v_me, completed_at = now()
   where id = p_match_id;
end $fn$;

-- ---------------------------------------------------------------- tournaments
create or replace function public.join_tournament(
  p_tournament_id uuid,
  p_team_name     text,
  p_partner_id    uuid default null
)
returns public.tournament_teams
language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_me   uuid := auth.uid();
  v_t    public.tournaments;
  v_team public.tournament_teams;
  v_count int;
begin
  if v_me is null then
    raise exception 'Sign in to enter a tournament.' using errcode = '28000';
  end if;

  select * into v_t from public.tournaments where id = p_tournament_id for update;
  if v_t.id is null then
    raise exception 'Tournament not found.' using errcode = '22023';
  end if;
  if v_t.status <> 'open' then
    raise exception 'Registration for this tournament is closed.' using errcode = '22023';
  end if;
  if now() > v_t.registration_closes_at then
    raise exception 'Registration for this tournament has closed.' using errcode = '22023';
  end if;
  if v_t.mode = 'doubles' and p_partner_id is null then
    raise exception 'Doubles tournaments need a partner.' using errcode = '22023';
  end if;
  if p_partner_id = v_me then
    raise exception 'Pick someone other than yourself as your partner.' using errcode = '22023';
  end if;

  select count(*) into v_count from public.tournament_teams where tournament_id = p_tournament_id;
  if v_count >= v_t.size then
    raise exception 'This tournament is full.' using errcode = '22023';
  end if;

  if p_partner_id is not null and exists (
      select 1 from public.tournament_teams
      where tournament_id = p_tournament_id
        and (player1_id = p_partner_id or player2_id = p_partner_id)) then
    raise exception 'Your partner is already entered with another team.' using errcode = '22023';
  end if;

  insert into public.tournament_teams (tournament_id, name, player1_id, player2_id)
  values (p_tournament_id, p_team_name, v_me, p_partner_id)
  returning * into v_team;

  if v_count + 1 >= v_t.size then
    update public.tournaments set status = 'locked' where id = p_tournament_id;
  end if;

  return v_team;
end $fn$;

-- Seeds the bracket by rating and creates every round up front, so the UI can
-- draw the full tree immediately and just fill in names as rounds resolve.
create or replace function public.generate_bracket(p_tournament_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_t      public.tournaments;
  v_rounds int;
  v_r      int;
  v_slots  int;
begin
  select * into v_t from public.tournaments where id = p_tournament_id for update;
  if v_t.id is null then
    raise exception 'Tournament not found.' using errcode = '22023';
  end if;
  if not exists (select 1 from public.clubs where id = v_t.club_id and owner_id = auth.uid()) then
    raise exception 'Only the host club can start this tournament.' using errcode = '42501';
  end if;
  if v_t.status = 'live' or v_t.status = 'completed' then
    raise exception 'This bracket has already been drawn.' using errcode = '22023';
  end if;

  -- seed strongest team first; a missing opponent becomes a bye
  with seeded as (
    select tt.id,
           row_number() over (
             order by coalesce(p1.rating, 1000) + coalesce(p2.rating, p1.rating, 1000) desc
           ) as seed
    from public.tournament_teams tt
    left join public.profiles p1 on p1.id = tt.player1_id
    left join public.profiles p2 on p2.id = tt.player2_id
    where tt.tournament_id = p_tournament_id
  )
  update public.tournament_teams tt set seed = s.seed from seeded s where tt.id = s.id;

  delete from public.tournament_matches where tournament_id = p_tournament_id;

  v_rounds := ceil(log(2, v_t.size));
  v_slots  := v_t.size / 2;

  -- round 1: classic 1-vs-N, 2-vs-(N-1) pairing
  insert into public.tournament_matches (tournament_id, round, slot, team1_id, team2_id, scheduled_at)
  select p_tournament_id, 1, g.slot,
         (select id from public.tournament_teams where tournament_id = p_tournament_id and seed = g.slot),
         (select id from public.tournament_teams where tournament_id = p_tournament_id and seed = v_t.size + 1 - g.slot),
         v_t.starts_at
  from generate_series(1, v_slots) as g(slot);

  -- empty shells for every later round
  for v_r in 2..v_rounds loop
    v_slots := v_slots / 2;
    insert into public.tournament_matches (tournament_id, round, slot)
    select p_tournament_id, v_r, g.slot from generate_series(1, v_slots) as g(slot);
  end loop;

  -- walk over byes immediately
  update public.tournament_matches
     set winner_team_id = team1_id
   where tournament_id = p_tournament_id and round = 1
     and team1_id is not null and team2_id is null;

  update public.tournaments set status = 'live' where id = p_tournament_id;

  -- push those byes into round 2
  perform public.sync_bracket(p_tournament_id);
end $fn$;

-- Propagates every decided result into the next round. Idempotent.
create or replace function public.sync_bracket(p_tournament_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_max_round int;
begin
  select max(round) into v_max_round from public.tournament_matches where tournament_id = p_tournament_id;

  for i in 1..coalesce(v_max_round, 1) - 1 loop
    update public.tournament_matches nxt
       set team1_id = case when src.slot % 2 = 1 then src.winner_team_id else nxt.team1_id end,
           team2_id = case when src.slot % 2 = 0 then src.winner_team_id else nxt.team2_id end
    from public.tournament_matches src
    where src.tournament_id = p_tournament_id
      and src.round = i
      and src.winner_team_id is not null
      and nxt.tournament_id = p_tournament_id
      and nxt.round = i + 1
      and nxt.slot = ceil(src.slot / 2.0);
  end loop;

  update public.tournaments t
     set champion_team_id = f.winner_team_id,
         status = 'completed'
  from public.tournament_matches f
  where f.tournament_id = p_tournament_id
    and f.round = v_max_round
    and f.winner_team_id is not null
    and t.id = p_tournament_id;
end $fn$;

create or replace function public.report_tournament_result(
  p_tournament_match_id uuid,
  p_winner_team_id      uuid,
  p_score               jsonb default null
)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_tm public.tournament_matches;
begin
  select * into v_tm from public.tournament_matches where id = p_tournament_match_id for update;
  if v_tm.id is null then
    raise exception 'Bracket match not found.' using errcode = '22023';
  end if;
  if p_winner_team_id not in (coalesce(v_tm.team1_id, '00000000-0000-0000-0000-000000000000'::uuid),
                              coalesce(v_tm.team2_id, '00000000-0000-0000-0000-000000000000'::uuid)) then
    raise exception 'That team is not in this bracket match.' using errcode = '22023';
  end if;

  -- the host club, or any player in the tie, may report
  if not exists (
    select 1 from public.tournaments t
    join public.clubs c on c.id = t.club_id
    where t.id = v_tm.tournament_id and c.owner_id = auth.uid()
  ) and not exists (
    select 1 from public.tournament_teams tt
    where tt.id in (v_tm.team1_id, v_tm.team2_id)
      and auth.uid() in (tt.player1_id, tt.player2_id)
  ) then
    raise exception 'Only the host club or a player in this tie can report it.' using errcode = '42501';
  end if;

  update public.tournament_matches
     set winner_team_id = p_winner_team_id, score = p_score
   where id = p_tournament_match_id;

  perform public.sync_bracket(v_tm.tournament_id);
end $fn$;

-- ---------------------------------------------------------------- club analytics
-- One round trip for the owner dashboard.
create or replace function public.club_stats(p_club_id uuid, p_days int default 30)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_from  timestamptz := now() - make_interval(days => p_days);
  v_club  public.clubs;
  v_courts int;
  v_out   jsonb;
begin
  select * into v_club from public.clubs where id = p_club_id;
  if v_club.id is null then
    raise exception 'Club not found.' using errcode = '22023';
  end if;
  if v_club.owner_id is distinct from auth.uid() then
    raise exception 'You do not manage this club.' using errcode = '42501';
  end if;

  select count(*) into v_courts from public.courts where club_id = p_club_id and is_active;

  with m as (
    select * from public.matches
    where club_id = p_club_id and starts_at >= v_from and status <> 'cancelled'
  ),
  players as (
    select mp.player_id, count(*) as plays, max(m.starts_at) as last_seen
    from m join public.match_players mp on mp.match_id = m.id
    group by mp.player_id
  )
  select jsonb_build_object(
    'currency',        v_club.currency,
    'courts',          v_courts,
    'matches',         (select count(*) from m),
    'completed',       (select count(*) from m where status = 'completed'),
    'revenue_cents',   (select coalesce(sum(price_total_cents), 0) from m),
    'hours_played',    (select coalesce(round(sum(extract(epoch from (ends_at - starts_at)) / 3600.0), 1), 0) from m),
    'unique_players',  (select count(*) from players),
    'repeat_players',  (select count(*) from players where plays > 1),
    'occupancy_pct',   (
      select case when v_courts = 0 then 0 else least(100, round(
        coalesce(sum(extract(epoch from (ends_at - starts_at)) / 3600.0), 0) * 100.0 /
        nullif(v_courts * p_days * greatest(1, extract(hour from (v_club.closes_at - v_club.opens_at))), 0)
      )) end from m),
    'peak_hours',      (
      select coalesce(jsonb_agg(x order by x.hour), '[]'::jsonb) from (
        select extract(hour from (starts_at at time zone v_club.timezone))::int as hour,
               count(*)::int as matches
        from m group by 1
      ) x),
    'daily',           (
      select coalesce(jsonb_agg(x order by x.day), '[]'::jsonb) from (
        select (starts_at at time zone v_club.timezone)::date as day,
               count(*)::int as matches,
               sum(price_total_cents)::int as revenue_cents
        from m group by 1
      ) x),
    'top_players',     (
      select coalesce(jsonb_agg(x), '[]'::jsonb) from (
        select pr.username, pr.full_name, pr.avatar_url, pr.level, pl.plays::int, pl.last_seen
        from players pl join public.profiles pr on pr.id = pl.player_id
        order by pl.plays desc limit 10
      ) x)
  ) into v_out;

  return v_out;
end $fn$;

-- ---------------------------------------------------------------- leaderboard
create or replace view public.leaderboard
with (security_invoker = on) as
select p.id, p.username, p.full_name, p.avatar_url, p.city, p.country,
       p.rating, p.level, p.matches_played, p.matches_won,
       case when p.matches_played > 0
            then round(p.matches_won::numeric * 100 / p.matches_played)
            else 0 end as win_pct,
       rank() over (partition by lower(p.city) order by p.rating desc, p.matches_won desc) as city_rank,
       rank() over (order by p.rating desc, p.matches_won desc) as global_rank
from public.profiles p
where p.matches_played > 0;

-- ---------------------------------------------------------------- RLS
alter table public.profiles           enable row level security;
alter table public.clubs              enable row level security;
alter table public.courts             enable row level security;
alter table public.matches            enable row level security;
alter table public.match_players      enable row level security;
alter table public.queue_entries      enable row level security;
alter table public.tournaments        enable row level security;
alter table public.tournament_teams   enable row level security;
alter table public.tournament_matches enable row level security;

create policy profiles_read   on public.profiles for select using (true);
create policy profiles_insert on public.profiles for insert with check (auth.uid() = id);
create policy profiles_update on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy clubs_read   on public.clubs for select using (status = 'active' or owner_id = auth.uid());
create policy clubs_insert on public.clubs for insert with check (auth.uid() = owner_id);
create policy clubs_update on public.clubs for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy clubs_delete on public.clubs for delete using (auth.uid() = owner_id);

create policy courts_read  on public.courts for select using (true);
create policy courts_write on public.courts for all
  using (exists (select 1 from public.clubs c where c.id = club_id and c.owner_id = auth.uid()))
  with check (exists (select 1 from public.clubs c where c.id = club_id and c.owner_id = auth.uid()));

-- Match history is public (it is what a leaderboard and a profile are made of).
-- Writes only ever happen through the security-definer functions above.
create policy matches_read on public.matches for select using (true);
create policy match_players_read on public.match_players for select using (true);

-- A queue entry is private: you see your own, the matcher sees everyone.
create policy queue_read   on public.queue_entries for select using (auth.uid() = player_id);
create policy queue_insert on public.queue_entries for insert with check (auth.uid() = player_id);
create policy queue_update on public.queue_entries for update using (auth.uid() = player_id);

create policy tournaments_read  on public.tournaments for select using (true);
create policy tournaments_write on public.tournaments for all
  using (exists (select 1 from public.clubs c where c.id = club_id and c.owner_id = auth.uid()))
  with check (exists (select 1 from public.clubs c where c.id = club_id and c.owner_id = auth.uid()));

create policy tteams_read   on public.tournament_teams for select using (true);
create policy tteams_delete on public.tournament_teams for delete
  using (auth.uid() in (player1_id, player2_id));

create policy tmatches_read on public.tournament_matches for select using (true);

-- ---------------------------------------------------------------- grants
grant usage on schema public to anon, authenticated, service_role;
grant select on all tables in schema public to anon, authenticated, service_role;
grant insert, update, delete on public.profiles, public.clubs, public.courts,
      public.queue_entries, public.tournaments, public.tournament_teams
      to authenticated;
grant execute on all functions in schema public to anon, authenticated, service_role;
alter default privileges in schema public grant select on tables to anon, authenticated, service_role;
alter default privileges in schema public grant execute on functions to anon, authenticated, service_role;

-- ---------------------------------------------------------------- queue pulse
-- How many players are waiting, without leaking who they are. A waiting room
-- that looks empty is the fastest way to make matchmaking feel broken.
create or replace function public.queue_pulse(p_play_date date, p_city text)
returns int language sql security definer stable
set search_path = public, pg_temp as $fn$
  select count(*)::int from public.queue_entries
  where status = 'waiting' and play_date = p_play_date and lower(city) = lower(p_city);
$fn$;
grant execute on function public.queue_pulse(date, text) to anon, authenticated;

-- ---------------------------------------------------------------- realtime
-- The waiting room subscribes to its own queue row and refreshes the instant
-- the matcher claims it.
alter publication supabase_realtime add table public.queue_entries;
alter publication supabase_realtime add table public.matches;

-- ============================ relocate seed to pakistan ============================

-- Relocate the demo estate from Dubai to Islamabad / Rawalpindi and make PKR
-- the default currency for new rows.
--
-- Safe on a fresh database: the delete simply matches nothing.
-- Run supabase/seed.sql afterwards to insert the new clubs.

alter table public.clubs       alter column currency set default 'PKR';
alter table public.matches     alter column currency set default 'PKR';
alter table public.tournaments alter column currency set default 'PKR';

-- Retire the original demo venues. Their courts cascade away with them.
--
-- matches.club_id is ON DELETE RESTRICT, so this deliberately fails if anyone
-- has actually booked one of these courts: demo data is disposable, a real
-- booking is not, and it should never disappear quietly.
delete from public.clubs
where slug in (
  'dune-padel-club',
  'marina-glass-courts',
  'jumeirah-padel-house',
  'desert-smash-arena',
  'creek-padel-yard',
  'silicon-oasis-padel'
);

-- Re-assert the realtime publication. It is the one piece of setup that cannot
-- be checked over the REST API, so make it self-healing rather than assumed.
--
-- Catches everything, not just duplicate_object: realtime is an enhancement,
-- and a publication that cannot be altered (ownership, a renamed publication)
-- must never abort the migration carrying the data changes.
do $realtime$
begin
  alter publication supabase_realtime add table public.queue_entries;
exception when others then
  raise notice 'realtime: queue_entries not added (%)', sqlerrm;
end $realtime$;

do $realtime$
begin
  alter publication supabase_realtime add table public.matches;
exception when others then
  raise notice 'realtime: matches not added (%)', sqlerrm;
end $realtime$;

-- ============================ owner results and chat ============================

-- Two changes:
--   1. Only the host club records a result. Players no longer score themselves.
--   2. Matched players get a private thread for the match.

-- ------------------------------------------------------------ result reporting
-- Previously any player in the match could report it, which means a player could
-- declare their own win. The club that hosted the match is the only neutral
-- party, so reporting moves to them.
--
-- Also refuses a result before the match has actually finished. That guard lives
-- here rather than only in the UI, because a hidden button is not a rule.
create or replace function public.report_match_result(
  p_match_id     uuid,
  p_winning_team smallint,
  p_score        jsonb default null
)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_k    constant int := 32;
  v_me   uuid := auth.uid();
  v_r1   numeric;
  v_r2   numeric;
  v_exp1 numeric;
  v_d1   int;
  v_d2   int;
begin
  if not exists (
    select 1
    from public.matches m
    join public.clubs c on c.id = m.club_id
    where m.id = p_match_id and c.owner_id = v_me
  ) then
    raise exception 'Only the host club can record this result.' using errcode = '42501';
  end if;

  if not exists (select 1 from public.matches where id = p_match_id and status = 'scheduled') then
    raise exception 'This match has already been settled.' using errcode = '22023';
  end if;

  if exists (select 1 from public.matches where id = p_match_id and ends_at > now()) then
    raise exception 'This match has not been played yet.' using errcode = '22023';
  end if;

  if p_winning_team not in (1, 2) then
    raise exception 'Winning team must be 1 or 2.' using errcode = '22023';
  end if;

  select avg(pr.rating) filter (where mp.team = 1),
         avg(pr.rating) filter (where mp.team = 2)
    into v_r1, v_r2
  from public.match_players mp
  join public.profiles pr on pr.id = mp.player_id
  where mp.match_id = p_match_id;

  v_exp1 := 1.0 / (1.0 + power(10.0, (v_r2 - v_r1) / 400.0));
  v_d1   := round(v_k * ((case when p_winning_team = 1 then 1 else 0 end) - v_exp1));
  v_d2   := -v_d1;

  update public.profiles p
     set rating         = greatest(100, least(4000, p.rating + case when mp.team = 1 then v_d1 else v_d2 end)),
         matches_played = p.matches_played + 1,
         matches_won    = p.matches_won + case when mp.team = p_winning_team then 1 else 0 end,
         updated_at     = now()
  from public.match_players mp
  where mp.match_id = p_match_id and mp.player_id = p.id;

  update public.match_players mp
     set rating_after = pr.rating
  from public.profiles pr
  where mp.match_id = p_match_id and pr.id = mp.player_id;

  update public.matches
     set status = 'completed', winning_team = p_winning_team, score = p_score,
         reported_by = v_me, completed_at = now()
   where id = p_match_id;
end $fn$;

-- ------------------------------------------------------------------- match chat
create table if not exists public.match_messages (
  id         uuid primary key default gen_random_uuid(),
  match_id   uuid not null references public.matches(id) on delete cascade,
  sender_id  uuid not null references public.profiles(id) on delete cascade,
  body       text not null,
  created_at timestamptz not null default now(),
  constraint message_length check (char_length(btrim(body)) between 1 and 1000)
);
create index if not exists match_messages_thread_idx
  on public.match_messages (match_id, created_at);

comment on table public.match_messages is
  'Private thread per match. Membership is the only key — there is no other way in.';

-- Membership test, extracted so both policies read plainly and Postgres can
-- cache the plan. security definer because the caller may not see match_players
-- rows for a match they are checking.
create or replace function public.is_match_player(p_match_id uuid)
returns boolean language sql stable security definer
set search_path = public, pg_temp as $fn$
  select exists (
    select 1 from public.match_players
    where match_id = p_match_id and player_id = auth.uid()
  );
$fn$;

alter table public.match_messages enable row level security;

drop policy if exists match_messages_read on public.match_messages;
create policy match_messages_read on public.match_messages for select
  using (public.is_match_player(match_id));

drop policy if exists match_messages_insert on public.match_messages;
create policy match_messages_insert on public.match_messages for insert
  with check (sender_id = auth.uid() and public.is_match_player(match_id));

-- No update or delete policy: a thread is a record of what was said. Editing
-- history in a chat four people rely on to agree a time is worse than a typo.

grant select, insert on public.match_messages to authenticated;
grant execute on function public.is_match_player(uuid) to authenticated;

do $realtime$
begin
  alter publication supabase_realtime add table public.match_messages;
exception when others then
  raise notice 'realtime: match_messages not added (%)', sqlerrm;
end $realtime$;

-- ============================ community bookings and owner accounts ============================

-- Community, collision-safe court booking, and owner onboarding.
--
-- The public calendar is backed by `matches`, so matchmaking and direct
-- bookings share one source of truth. A trigger serialises writes per court and
-- rejects every overlap, including different start times.

-- ------------------------------------------------------------- account type
-- This flag is presentation state only. Ownership authorization continues to
-- come from clubs.owner_id, never editable auth user metadata.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $fn$
begin
  insert into public.profiles (id, username, full_name, city, country, is_club_owner)
  values (
    new.id,
    coalesce(
      nullif(lower(new.raw_user_meta_data->>'username'), ''),
      'p' || substr(replace(new.id::text, '-', ''), 1, 12)
    ),
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), 'Player'),
    nullif(new.raw_user_meta_data->>'city', ''),
    nullif(new.raw_user_meta_data->>'country', ''),
    coalesce(new.raw_user_meta_data->>'account_type', '') = 'club_owner'
  )
  on conflict (id) do nothing;
  return new;
exception when others then
  return new;
end $fn$;

-- ----------------------------------------------------------- direct booking
alter table public.matches
  add column if not exists booked_by uuid references public.profiles(id) on delete set null;

create index if not exists matches_court_window_idx
  on public.matches (court_id, starts_at, ends_at)
  where status <> 'cancelled';
create index if not exists matches_booked_by_idx
  on public.matches (booked_by, starts_at desc)
  where booked_by is not null;

-- Client date limits are convenience; these guards are the actual rule.
create or replace function public.validate_queue_date()
returns trigger language plpgsql set search_path = public, pg_temp as $fn$
begin
  if new.play_date < current_date then
    raise exception 'Pick today or a future date.' using errcode = '22023';
  end if;
  if new.play_date > current_date + 14 then
    raise exception 'Matchmaking opens 14 days ahead.' using errcode = '22023';
  end if;
  return new;
end $fn$;

drop trigger if exists queue_validate_date on public.queue_entries;
create trigger queue_validate_date
  before insert or update of play_date on public.queue_entries
  for each row execute function public.validate_queue_date();

do $constraints$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.queue_entries'::regclass
      and conname = 'queue_level_bounds'
  ) then
    alter table public.queue_entries add constraint queue_level_bounds
      check (min_level between 1.0 and 7.0 and max_level between 1.0 and 7.0);
  end if;
end $constraints$;

create or replace function public.prevent_overlapping_match()
returns trigger language plpgsql security definer
set search_path = public, pg_temp as $fn$
begin
  if new.status = 'cancelled' then
    return new;
  end if;

  -- Serialise only this court. This closes the race between two bookings that
  -- both saw the slot as free before either insert committed.
  perform pg_advisory_xact_lock(hashtext(new.court_id::text));

  if exists (
    select 1
    from public.matches m
    where m.court_id = new.court_id
      and m.id <> new.id
      and m.status <> 'cancelled'
      and m.starts_at < new.ends_at
      and m.ends_at > new.starts_at
  ) then
    raise exception 'That court is already booked during this time.'
      using errcode = '23P01';
  end if;

  return new;
end $fn$;

drop trigger if exists matches_prevent_overlap on public.matches;
create trigger matches_prevent_overlap
  before insert or update of court_id, starts_at, ends_at, status on public.matches
  for each row execute function public.prevent_overlapping_match();

create or replace function public.book_court(
  p_court_id  uuid,
  p_play_date date,
  p_start_time time
)
returns public.matches
language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_me uuid := auth.uid();
  v_club public.clubs;
  v_match public.matches;
  v_starts timestamptz;
  v_ends timestamptz;
  v_duration constant interval := interval '90 minutes';
begin
  if v_me is null then
    raise exception 'Sign in to book a court.' using errcode = '28000';
  end if;

  select cl.* into v_club
  from public.courts c
  join public.clubs cl on cl.id = c.club_id
  where c.id = p_court_id and c.is_active and cl.status = 'active';

  if v_club.id is null then
    raise exception 'That court is not available.' using errcode = '22023';
  end if;
  if p_play_date > (now() at time zone v_club.timezone)::date + 60 then
    raise exception 'Bookings open 60 days ahead.' using errcode = '22023';
  end if;
  if p_start_time < v_club.opens_at
     or p_start_time + v_duration > v_club.closes_at then
    raise exception 'Pick a 90-minute slot inside the club opening hours.' using errcode = '22023';
  end if;

  v_starts := (p_play_date + p_start_time) at time zone v_club.timezone;
  v_ends := v_starts + v_duration;
  if v_starts <= now() + interval '5 minutes' then
    raise exception 'Pick a future time.' using errcode = '22023';
  end if;

  insert into public.matches
    (club_id, court_id, mode, starts_at, ends_at, origin,
     price_total_cents, currency, booked_by)
  values
    (v_club.id, p_court_id, 'doubles', v_starts, v_ends, 'direct',
     round(v_club.price_per_hour_cents * 1.5), v_club.currency, v_me)
  returning * into v_match;

  -- The organiser owns the booking and sees it in their match history. Direct
  -- bookings do not affect ratings until a complete roster exists.
  insert into public.match_players (match_id, player_id, team, rating_before)
  select v_match.id, p.id, 1, p.rating
  from public.profiles p where p.id = v_me;

  return v_match;
exception
  when exclusion_violation or unique_violation then
    raise exception 'That court was just booked by someone else.' using errcode = '23P01';
end $fn$;

create or replace function public.cancel_direct_booking(p_match_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
begin
  update public.matches m
     set status = 'cancelled'
   where m.id = p_match_id
     and m.origin = 'direct'
     and m.status = 'scheduled'
     and m.starts_at > now()
     and (
       m.booked_by = auth.uid()
       or exists (
         select 1 from public.clubs c
         where c.id = m.club_id and c.owner_id = auth.uid()
       )
     );

  if not found then
    raise exception 'This booking cannot be cancelled.' using errcode = '42501';
  end if;
end $fn$;

revoke all on function public.prevent_overlapping_match() from public, anon, authenticated;
revoke all on function public.book_court(uuid, date, time) from public, anon;
revoke all on function public.cancel_direct_booking(uuid) from public, anon;
grant execute on function public.book_court(uuid, date, time) to authenticated;
grant execute on function public.cancel_direct_booking(uuid) to authenticated;

-- ---------------------------------------------------------- community chat
create table if not exists public.community_messages (
  id         uuid primary key default gen_random_uuid(),
  sender_id  uuid not null references public.profiles(id) on delete cascade,
  body       text not null,
  created_at timestamptz not null default now(),
  constraint community_message_length
    check (char_length(btrim(body)) between 1 and 1000)
);

create index if not exists community_messages_recent_idx
  on public.community_messages (created_at desc);

alter table public.community_messages enable row level security;

drop policy if exists community_messages_read on public.community_messages;
create policy community_messages_read on public.community_messages for select
  to authenticated
  using (created_at >= now() - interval '7 days');

drop policy if exists community_messages_insert on public.community_messages;
create policy community_messages_insert on public.community_messages for insert
  to authenticated
  with check (sender_id = (select auth.uid()) and created_at >= now() - interval '1 minute');

grant select, insert on public.community_messages to authenticated;

-- Physical retention runs hourly when pg_cron is available. The insert trigger
-- is a second line of defence and also keeps local/dev databases tidy.
create or replace function public.prune_community_messages()
returns integer language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_deleted integer;
begin
  delete from public.community_messages
  where created_at < now() - interval '7 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end $fn$;

create or replace function public.prune_community_messages_on_write()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $fn$
begin
  perform public.prune_community_messages();
  return null;
end $fn$;

drop trigger if exists community_messages_prune on public.community_messages;
create trigger community_messages_prune
  after insert on public.community_messages
  for each statement execute function public.prune_community_messages_on_write();

revoke all on function public.prune_community_messages() from public, anon, authenticated;
revoke all on function public.prune_community_messages_on_write() from public, anon, authenticated;

do $cron_setup$
begin
  begin
    create extension if not exists pg_cron with schema pg_catalog;
  exception when others then
    raise notice 'cron: extension unavailable (%); write-trigger retention remains active', sqlerrm;
  end;

  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.unschedule(jobid)
    from cron.job where jobname = 'volea-prune-community-messages';
    perform cron.schedule(
      'volea-prune-community-messages',
      '17 * * * *',
      $command$select public.prune_community_messages();$command$
    );
  end if;
exception when others then
  raise notice 'cron: schedule unavailable (%); write-trigger retention remains active', sqlerrm;
end $cron_setup$;

do $realtime$
begin
  alter publication supabase_realtime add table public.community_messages;
exception when others then
  raise notice 'realtime: community_messages not added (%)', sqlerrm;
end $realtime$;

-- Presence and the low-latency Broadcast path share one private channel. Only
-- a valid authenticated JWT may announce, send, or observe it. Realtime does
-- not persist these payloads in this table; community_messages is the durable
-- seven-day record.
drop policy if exists "volea community presence read" on realtime.messages;
drop policy if exists "volea community realtime read" on realtime.messages;
create policy "volea community realtime read"
on realtime.messages for select to authenticated
using (
  (select realtime.topic()) = 'community:lobby'
  and realtime.messages.extension in ('presence', 'broadcast')
);

drop policy if exists "volea community presence write" on realtime.messages;
drop policy if exists "volea community realtime write" on realtime.messages;
create policy "volea community realtime write"
on realtime.messages for insert to authenticated
with check (
  (select realtime.topic()) = 'community:lobby'
  and realtime.messages.extension in ('presence', 'broadcast')
);

-- Security hardening for existing definer helpers. Public is implicit in
-- Postgres, so grants to authenticated alone are not enough without this revoke.
revoke all on function public.is_match_player(uuid) from public, anon;
grant execute on function public.is_match_player(uuid) to authenticated;

comment on table public.community_messages is
  'Authenticated community lobby. Messages are visible for and deleted after seven days.';
comment on column public.matches.booked_by is
  'Organizer for a direct court reservation. Null for matchmade and tournament matches.';

-- ------------------------------------------------------- result concurrency
-- Lock the match before checking status so two owner tabs can never apply Elo
-- twice. A complete roster is required; a one-person direct court reservation
-- is a booking, not a rated match.
create or replace function public.report_match_result(
  p_match_id     uuid,
  p_winning_team smallint,
  p_score        jsonb default null
)
returns void language plpgsql security definer set search_path = public, pg_temp as $fn$
declare
  v_k    constant int := 32;
  v_me   uuid := auth.uid();
  v_match public.matches;
  v_r1   numeric;
  v_r2   numeric;
  v_exp1 numeric;
  v_d1   int;
  v_d2   int;
  v_t1   int;
  v_t2   int;
  v_each int;
begin
  select * into v_match
  from public.matches where id = p_match_id for update;

  if v_match.id is null then
    raise exception 'Match not found.' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.clubs c
    where c.id = v_match.club_id and c.owner_id = v_me
  ) then
    raise exception 'Only the host club can record this result.' using errcode = '42501';
  end if;
  if v_match.status <> 'scheduled' then
    raise exception 'This match has already been settled.' using errcode = '22023';
  end if;
  if v_match.ends_at > now() then
    raise exception 'This match has not been played yet.' using errcode = '22023';
  end if;
  if p_winning_team not in (1, 2) then
    raise exception 'Winning team must be 1 or 2.' using errcode = '22023';
  end if;

  select count(*) filter (where team = 1), count(*) filter (where team = 2)
    into v_t1, v_t2
  from public.match_players where match_id = p_match_id;
  v_each := case when v_match.mode = 'singles' then 1 else 2 end;
  if v_t1 <> v_each or v_t2 <> v_each then
    raise exception 'A rated % match needs % player(s) on each team.', v_match.mode, v_each
      using errcode = '22023';
  end if;

  select avg(pr.rating) filter (where mp.team = 1),
         avg(pr.rating) filter (where mp.team = 2)
    into v_r1, v_r2
  from public.match_players mp
  join public.profiles pr on pr.id = mp.player_id
  where mp.match_id = p_match_id;

  v_exp1 := 1.0 / (1.0 + power(10.0, (v_r2 - v_r1) / 400.0));
  v_d1 := round(v_k * ((case when p_winning_team = 1 then 1 else 0 end) - v_exp1));
  v_d2 := -v_d1;

  update public.profiles p
     set rating = greatest(100, least(4000,
           p.rating + case when mp.team = 1 then v_d1 else v_d2 end)),
         matches_played = p.matches_played + 1,
         matches_won = p.matches_won + case when mp.team = p_winning_team then 1 else 0 end,
         updated_at = now()
  from public.match_players mp
  where mp.match_id = p_match_id and mp.player_id = p.id;

  update public.match_players mp
     set rating_after = pr.rating
  from public.profiles pr
  where mp.match_id = p_match_id and pr.id = mp.player_id;

  update public.matches
     set status = 'completed', winning_team = p_winning_team, score = p_score,
         reported_by = v_me, completed_at = now()
   where id = p_match_id;
end $fn$;

revoke all on function public.report_match_result(uuid, smallint, jsonb) from public, anon;
grant execute on function public.report_match_result(uuid, smallint, jsonb) to authenticated;

-- ============================ demo clubs ============================

-- Volea demo seed — fictional clubs, real geography (Islamabad / Rawalpindi).
-- Club names are invented so nothing impersonates a real business; the sectors,
-- schemes and coordinates are genuine.
-- Safe to re-run: every insert is keyed on slug / (club, court name).

insert into public.clubs
  (name, slug, description, address, city, country, lat, lng, timezone,
   phone, price_per_hour_cents, currency, opens_at, closes_at, amenities, status)
values
  -- ---------------------------------------------------------------- Islamabad
  ('Margalla Padel Club', 'margalla-padel-club',
   'Four panoramic courts under the Margalla hills, floodlit until midnight.',
   'F-7 Markaz', 'Islamabad', 'PK', 33.7180, 73.0560, 'Asia/Karachi',
   '+92 51 000 0001', 850000, 'PKR', '06:00', '23:59',
   array['Floodlights','Pro shop','Showers','Cafe'], 'active'),

  ('Kohsar Padel Courts', 'kohsar-padel-courts',
   'Two courts tucked behind Super Market. The 7am crowd is serious.',
   'F-6/3 Super Market', 'Islamabad', 'PK', 33.7294, 73.0797, 'Asia/Karachi',
   '+92 51 000 0002', 900000, 'PKR', '06:00', '23:00',
   array['Floodlights','Coaching','Parking'], 'active'),

  ('Blue Area Padel Deck', 'blue-area-padel-deck',
   'Rooftop courts over Jinnah Avenue. Indoor, so the monsoon is somebody else''s problem.',
   'Jinnah Avenue, Blue Area', 'Islamabad', 'PK', 33.7100, 73.0600, 'Asia/Karachi',
   '+92 51 000 0003', 1000000, 'PKR', '07:00', '23:59',
   array['Indoor','Rooftop','Air conditioned','Cafe'], 'active'),

  ('E-11 Padel Park', 'e11-padel-park',
   'Community club on the western edge. Cheapest peak-hour rate in the sector.',
   'E-11/2', 'Islamabad', 'PK', 33.7010, 72.9720, 'Asia/Karachi',
   '+92 51 000 0004', 650000, 'PKR', '06:00', '23:59',
   array['Floodlights','Racket hire','Parking'], 'active'),

  ('G-13 Padel Courts', 'g13-padel-courts',
   'Three courts beside the service road. Friendly Sunday mixers.',
   'G-13/1', 'Islamabad', 'PK', 33.6470, 72.9310, 'Asia/Karachi',
   '+92 51 000 0005', 600000, 'PKR', '06:00', '23:30',
   array['Floodlights','Racket hire','Mixers'], 'active'),

  -- --------------------------------------------------------------- Rawalpindi
  ('Bahria Padel Arena', 'bahria-padel-arena',
   'Six courts, the largest padel venue in the twin cities.',
   'Bahria Town Phase 4', 'Rawalpindi', 'PK', 33.5227, 73.0960, 'Asia/Karachi',
   '+92 51 000 0006', 780000, 'PKR', '06:00', '23:59',
   array['Floodlights','Pro shop','Showers','Cafe','Parking'], 'active'),

  ('Chaklala Padel Club', 'chaklala-padel-club',
   'Two floodlit courts off the Scheme 3 main road.',
   'Chaklala Scheme 3', 'Rawalpindi', 'PK', 33.5860, 73.0980, 'Asia/Karachi',
   '+92 51 000 0007', 620000, 'PKR', '06:00', '23:30',
   array['Floodlights','Racket hire'], 'active'),

  ('Askari Padel Courts', 'askari-padel-courts',
   'Three courts off Airport Road, ten minutes from the motorway.',
   'Askari 14', 'Rawalpindi', 'PK', 33.5730, 73.1250, 'Asia/Karachi',
   '+92 51 000 0008', 720000, 'PKR', '06:00', '23:59',
   array['Floodlights','Coaching','Cafe','Parking'], 'active')
on conflict (slug) do nothing;

-- Courts per club
insert into public.courts (club_id, name, indoor, surface)
select c.id, v.name, v.indoor, 'artificial grass'
from public.clubs c
join (values
  ('margalla-padel-club',  'Court 1', false), ('margalla-padel-club',  'Court 2', false),
  ('margalla-padel-club',  'Court 3', false), ('margalla-padel-club',  'Court 4', false),
  ('kohsar-padel-courts',  'Court 1', false), ('kohsar-padel-courts',  'Court 2', false),
  ('blue-area-padel-deck', 'Deck A',   true), ('blue-area-padel-deck', 'Deck B',   true),
  ('e11-padel-park',       'Court 1', false), ('e11-padel-park',       'Court 2', false),
  ('e11-padel-park',       'Court 3', false),
  ('g13-padel-courts',     'Court 1', false), ('g13-padel-courts',     'Court 2', false),
  ('g13-padel-courts',     'Court 3', false),
  ('bahria-padel-arena',   'Court 1', false), ('bahria-padel-arena',   'Court 2', false),
  ('bahria-padel-arena',   'Court 3', false), ('bahria-padel-arena',   'Court 4', false),
  ('bahria-padel-arena',   'Court 5', false), ('bahria-padel-arena',   'Court 6', false),
  ('chaklala-padel-club',  'Court 1', false), ('chaklala-padel-club',  'Court 2', false),
  ('askari-padel-courts',  'Court 1', false), ('askari-padel-courts',  'Court 2', false),
  ('askari-padel-courts',  'Court 3', false)
) as v(slug, name, indoor) on v.slug = c.slug
on conflict (club_id, name) do nothing;

-- Report what actually landed. A seed that quietly inserts nothing looks
-- identical to a seed that was never run, and the app just says "no clubs".
select
  (select count(*) from public.clubs)  as clubs,
  (select count(*) from public.courts) as courts;

-- ============================ self-check ============================

-- Volea end-to-end database self-check. Run against a disposable/dev database:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/tests/matchmaking.test.sql
--
-- Covers doubles + singles, pinned + automatic venue selection, intersecting
-- windows, two-way level bands, conflicting clubs, collision-safe direct
-- bookings, owner-only results, Elo, community retention, and cleanup.

do $test$
declare
  v_ids uuid[] := array[
    gen_random_uuid(), gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
    gen_random_uuid(), gen_random_uuid(), gen_random_uuid()
  ];
  v_owner uuid := v_ids[7];
  v_club1 uuid := gen_random_uuid();
  v_club2 uuid := gen_random_uuid();
  v_court1 uuid := gen_random_uuid();
  v_court2 uuid := gen_random_uuid();
  v_entry public.queue_entries;
  v_match public.matches;
  v_direct public.matches;
  v_n int;
  v_t1 int;
  v_t2 int;
  v_before int;
  v_after int;
  v_windows time[][] := array[
    array['18:00'::time, '22:00'::time],
    array['19:00'::time, '23:00'::time],
    array['20:00'::time, '23:00'::time],
    array['20:30'::time, '23:00'::time]
  ];
begin
  for i in 1..7 loop
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password,
      email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
      created_at, updated_at
    ) values (
      v_ids[i], '00000000-0000-0000-0000-000000000000',
      'authenticated', 'authenticated', 'p' || i || '@volea.test', '', now(),
      '{"provider":"email"}'::jsonb,
      jsonb_build_object(
        'username', 'tester' || i,
        'full_name', case when i = 7 then 'Test Owner' else 'Tester ' || i end,
        'city', 'Volea Test City',
        'account_type', case when i = 7 then 'club_owner' else 'player' end
      ),
      now(), now()
    );
  end loop;

  if not (select is_club_owner from public.profiles where id = v_owner) then
    raise exception 'FAIL: owner signup metadata did not produce an owner profile';
  end if;

  insert into public.clubs (
    id, owner_id, name, slug, city, country, lat, lng, timezone,
    price_per_hour_cents, currency, opens_at, closes_at, status
  ) values
    (v_club1, v_owner, 'Volea Test Club A', 'volea-test-club-a',
     'Volea Test City', 'PK', 33.7, 73.0, 'Asia/Karachi',
     600000, 'PKR', '06:00', '23:30', 'active'),
    (v_club2, v_owner, 'Volea Test Club B', 'volea-test-club-b',
     'Volea Test City', 'PK', 33.71, 73.01, 'Asia/Karachi',
     700000, 'PKR', '06:00', '23:30', 'active');
  insert into public.courts (id, club_id, name) values
    (v_court1, v_club1, 'Test Court A'),
    (v_court2, v_club2, 'Test Court B');

  -- Doubles, pinned club, and the running intersection of four windows.
  for i in 1..3 loop
    perform set_config('request.jwt.claims', json_build_object('sub', v_ids[i])::text, true);
    v_entry := public.join_queue(
      current_date + 1, v_windows[i][1], v_windows[i][2],
      'doubles', v_club1, 1.0, 7.0
    );
    if v_entry.status <> 'waiting' then
      raise exception 'FAIL: doubles matched before player four';
    end if;
  end loop;

  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[4])::text, true);
  v_entry := public.join_queue(
    current_date + 1, v_windows[4][1], v_windows[4][2],
    'doubles', v_club1, 1.0, 7.0
  );
  if v_entry.status <> 'matched' or v_entry.match_id is null then
    raise exception 'FAIL: fourth compatible doubles player did not complete the match';
  end if;

  select * into v_match from public.matches where id = v_entry.match_id;
  if v_match.club_id <> v_club1 or v_match.court_id <> v_court1 then
    raise exception 'FAIL: pinned club/court was not respected';
  end if;
  if (v_match.starts_at at time zone 'Asia/Karachi')::time <> '20:30'::time
     or v_match.ends_at - v_match.starts_at <> interval '90 minutes' then
    raise exception 'FAIL: running window intersection did not produce 20:30-22:00';
  end if;

  select count(*), count(*) filter (where team = 1), count(*) filter (where team = 2)
    into v_n, v_t1, v_t2
  from public.match_players where match_id = v_match.id;
  if v_n <> 4 or v_t1 <> 2 or v_t2 <> 2 then
    raise exception 'FAIL: doubles roster is %, split %/%', v_n, v_t1, v_t2;
  end if;

  -- Owner-only result, locked and applied once. Move the synthetic match into
  -- the past because production correctly refuses scores before full time.
  update public.matches
     set starts_at = now() - interval '2 hours', ends_at = now() - interval '30 minutes'
   where id = v_match.id;
  select rating into v_before from public.profiles where id = v_ids[1];
  perform set_config('request.jwt.claims', json_build_object('sub', v_owner)::text, true);
  perform public.report_match_result(v_match.id, 1::smallint, '[[6,4],[6,3]]'::jsonb);
  select rating into v_after from public.profiles where id = v_ids[1];
  if v_after <= v_before then
    raise exception 'FAIL: winning rating did not rise (% -> %)', v_before, v_after;
  end if;
  begin
    perform public.report_match_result(v_match.id, 2::smallint, null);
    raise exception 'FAIL: the same result was applied twice';
  exception when sqlstate '22023' then null;
  end;

  -- Singles with automatic venue selection.
  for i in 5..6 loop
    perform set_config('request.jwt.claims', json_build_object('sub', v_ids[i])::text, true);
    v_entry := public.join_queue(
      current_date + 2, '10:00', '12:00', 'singles', null, 1.0, 7.0
    );
  end loop;
  if v_entry.status <> 'matched' or v_entry.match_id is null then
    raise exception 'FAIL: two compatible singles players did not match';
  end if;
  select count(*), count(*) filter (where team = 1), count(*) filter (where team = 2)
    into v_n, v_t1, v_t2
  from public.match_players where match_id = v_entry.match_id;
  if v_n <> 2 or v_t1 <> 1 or v_t2 <> 1 then
    raise exception 'FAIL: singles roster is %, split %/%', v_n, v_t1, v_t2;
  end if;

  -- Two-way level compatibility.
  update public.profiles set rating = 2500 where id = v_ids[6];
  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[5])::text, true);
  perform public.join_queue(current_date + 3, '18:00', '21:00', 'singles', v_club1, 1.0, 2.5);
  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[6])::text, true);
  v_entry := public.join_queue(current_date + 3, '18:00', '21:00', 'singles', v_club1, 6.0, 7.0);
  if v_entry.status <> 'waiting' then
    raise exception 'FAIL: mutually incompatible level bands matched';
  end if;

  -- Conflicting club pins.
  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[5])::text, true);
  perform public.join_queue(current_date + 4, '18:00', '21:00', 'singles', v_club1, 1.0, 7.0);
  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[6])::text, true);
  v_entry := public.join_queue(current_date + 4, '18:00', '21:00', 'singles', v_club2, 1.0, 7.0);
  if v_entry.status <> 'waiting' then
    raise exception 'FAIL: players who pinned different clubs matched';
  end if;

  -- Direct booking and a differently-started overlapping booking.
  perform set_config('request.jwt.claims', json_build_object('sub', v_ids[1])::text, true);
  v_direct := public.book_court(v_court1, current_date + 6, '10:00');
  if v_direct.origin <> 'direct' or v_direct.booked_by <> v_ids[1]
     or v_direct.price_total_cents <> 900000 then
    raise exception 'FAIL: direct booking snapshot is incorrect';
  end if;
  begin
    perform public.book_court(v_court1, current_date + 6, '10:30');
    raise exception 'FAIL: overlapping booking was allowed';
  exception when sqlstate '23P01' then null;
  end;

  -- Seven-day community retention.
  insert into public.community_messages (sender_id, body, created_at)
  values (v_ids[1], 'expired test message', now() - interval '8 days');
  perform public.prune_community_messages();
  if exists (select 1 from public.community_messages where body = 'expired test message') then
    raise exception 'FAIL: expired community message was not pruned';
  end if;

  raise notice 'PASS: matchmaking settings, booking collisions, owner results, rankings input and chat retention are green';

  delete from public.matches where club_id in (v_club1, v_club2);
  delete from public.clubs where id in (v_club1, v_club2);
  delete from auth.users where id = any(v_ids);
end $test$;
